name: Build Vue.js app

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - run: npm install
      - run: npm run build
      
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: Website
          path: ./dist/